// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3b7g7N7J8ij9qFhpy89Hjuuhk30DMW0Y',
    appId: '1:582765394027:web:6afe1643972ba8138d192e',
    messagingSenderId: '582765394027',
    projectId: 'lekol-pam-d3457',
    authDomain: 'lekol-pam-d3457.firebaseapp.com',
    storageBucket: 'lekol-pam-d3457.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_8DZ9docbPbcohMWvVuRWvrjQz4cm3kI',
    appId: '1:582765394027:android:ab5ebff6300567d08d192e',
    messagingSenderId: '582765394027',
    projectId: 'lekol-pam-d3457',
    storageBucket: 'lekol-pam-d3457.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA74FxUg1j1__zjLK-m3XFTtdYDSHxqEus',
    appId: '1:582765394027:ios:cc7f2f6c26b32a8d8d192e',
    messagingSenderId: '582765394027',
    projectId: 'lekol-pam-d3457',
    storageBucket: 'lekol-pam-d3457.appspot.com',
    iosClientId: '582765394027-75eshi6msj56lhlkocddn1b0223j4udf.apps.googleusercontent.com',
    iosBundleId: 'com.example.lekolMwen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA74FxUg1j1__zjLK-m3XFTtdYDSHxqEus',
    appId: '1:582765394027:ios:cc7f2f6c26b32a8d8d192e',
    messagingSenderId: '582765394027',
    projectId: 'lekol-pam-d3457',
    storageBucket: 'lekol-pam-d3457.appspot.com',
    iosClientId: '582765394027-75eshi6msj56lhlkocddn1b0223j4udf.apps.googleusercontent.com',
    iosBundleId: 'com.example.lekolMwen',
  );
}
